# Generated by Django 5.2.5 on 2025-09-03 19:40

import autoslug.fields
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hosts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('bio', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Hosts',
            },
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tags', models.CharField(help_text='Enter a tag', max_length=30)),
            ],
            options={
                'verbose_name_plural': 'Tags',
            },
        ),
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.IntegerField(null=True)),
                ('episode', models.IntegerField(null=True)),
                ('title', models.CharField(max_length=200)),
                ('link', models.CharField(help_text='Provide embed link to episode audio', max_length=1500)),
                ('googlepodcast', models.CharField(default='https://podcasts.google.com/feed/aHR0cHM6Ly9hbmNob3IuZm0vcy80ZDg4MWJhMC9wb2RjYXN0L3Jzcw?sa=X&ved=2ahUKEwjFxoL134D7AhUugc4BHXz1BeQQ9sEGegQIARAC', help_text='Provide link to episode on Google Podcasts', max_length=1500)),
                ('applepodcast', models.CharField(default='https://podcasts.apple.com/us/podcast/geospatially-africa-podcast-the-podcast-for/id1561204113', help_text='Provide link to episode on Apple Podcasts', max_length=1500)),
                ('spotify', models.CharField(default='https://open.spotify.com/show/7aqyurtRoF42hTysOqNa9v?si=9779d6cefca74f82', help_text='Provide link to episode on Spotify', max_length=1500)),
                ('summary', models.CharField(max_length=1500)),
                ('description', models.TextField()),
                ('host', models.CharField(choices=[('Iniobong Benson', 'Iniobong'), ('Opeyemi Kazeem-Jimoh', 'Opeyemi')], max_length=500)),
                ('cohost', models.CharField(blank=True, choices=[('Iniobong Benson', 'Iniobong'), ('Opeyemi Kazeem-Jimoh', 'Opeyemi')], max_length=500, null=True)),
                ('guest', models.CharField(max_length=200)),
                ('guest_bio', models.CharField(default='This is the guest bio', max_length=1000)),
                ('guest_image', models.ImageField(blank=True, upload_to='guest_image')),
                ('slug', autoslug.fields.AutoSlugField(default='slug', editable=False, populate_from='title', unique=True)),
                ('episode_image', models.ImageField(blank=True, upload_to='podcast_art/')),
                ('created_date', models.DateTimeField(default=datetime.datetime.now)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('tag', models.ManyToManyField(help_text='select a tag', to='podcast.tags')),
            ],
        ),
    ]
