# Generated by Django 3.2.6 on 2022-06-12 10:03

import autoslug.fields
import ckeditor.fields
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hosts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('bio', ckeditor.fields.RichTextField()),
            ],
            options={
                'verbose_name_plural': 'Hosts',
            },
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tags', models.CharField(help_text='Enter a tag', max_length=30)),
            ],
            options={
                'verbose_name_plural': 'Tags',
            },
        ),
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.IntegerField(null=True)),
                ('episode', models.IntegerField(null=True)),
                ('title', models.CharField(max_length=200)),
                ('link', models.CharField(help_text='Provide link to episode audio', max_length=1500)),
                ('summary', models.CharField(max_length=1500)),
                ('description', ckeditor.fields.RichTextField()),
                ('host', models.CharField(choices=[('Iniobong Benson', 'Iniobong'), ('Opeyemi Kazeem-Jimoh', 'Opeyemi')], max_length=500)),
                ('guest', models.CharField(max_length=200)),
                ('guest_bio', models.CharField(default='This is the guest bio', max_length=1000)),
                ('guest_image', models.ImageField(blank=True, upload_to='guest_image')),
                ('slug', autoslug.fields.AutoSlugField(default='slug', editable=False, populate_from='title')),
                ('episode_image', models.ImageField(blank=True, upload_to='podcast_art/')),
                ('created_date', models.DateTimeField(default=datetime.datetime.now)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('tag', models.ManyToManyField(help_text='select a tag', to='podcast.Tags')),
            ],
        ),
    ]
