# Generated by Django 5.2.5 on 2025-10-16 19:39

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcast', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='cohost',
            field=models.CharField(blank=True, choices=[('Iniobong Benson', 'Iniobong'), ('Opeyemi Kazeem-Jimoh', 'Opeyemi'), ('David Udoh', 'David')], max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='episode',
            name='host',
            field=models.CharField(choices=[('Iniobong Benson', 'Iniobong'), ('Opeyemi Kazeem-Jimoh', 'Opeyemi'), ('David Udoh', 'David')], max_length=500),
        ),
        migrations.AlterField(
            model_name='episode',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='title', unique=True),
        ),
    ]
