# Generated by Django 3.2.6 on 2021-08-08 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcast', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='episode',
            old_name='desc',
            new_name='description',
        ),
        migrations.AddField(
            model_name='episode',
            name='tags',
            field=models.CharField(default='Another great episode', max_length=60),
            preserve_default=False,
        ),
    ]
