# Generated by Django 3.2.6 on 2021-08-12 12:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('podcast', '0002_auto_20210808_0948'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='episode',
            field=models.IntegerField(1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='episode',
            name='season',
            field=models.IntegerField(1),
            preserve_default=False,
        ),
    ]
