# Generated by Django 4.2 on 2023-04-11 22:49

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('podcast', '0003_auto_20221027_1748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='slug',
            field=autoslug.fields.AutoSlugField(default='slug', editable=False, populate_from='title', unique=True),
        ),
    ]
