# Generated by Django 3.2.6 on 2021-08-12 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('podcast', '0003_auto_20210812_1322'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='episode',
            name='episode',
        ),
        migrations.RemoveField(
            model_name='episode',
            name='season',
        ),
    ]
