# Generated by Django 3.2.6 on 2023-04-20 21:27

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('podcast', '0004_alter_episode_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='title', unique=True),
        ),
    ]
