# Generated by Django 3.2.6 on 2021-08-12 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcast', '0004_auto_20210812_1327'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='episode',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='episode',
            name='season',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
