# Generated by Django 3.2.6 on 2021-08-12 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcast', '0005_auto_20210812_1329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='episode',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='episode',
            name='season',
            field=models.IntegerField(null=True),
        ),
    ]
