# Generated by Django 3.2.6 on 2021-08-12 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcast', '0006_auto_20210812_1331'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='link',
            field=models.CharField(default='https', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='episode',
            name='tags',
            field=models.CharField(max_length=20),
        ),
    ]
