# Generated by Django 3.2.6 on 2021-08-23 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcast', '0007_auto_20210812_2038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='link',
            field=models.CharField(max_length=300),
        ),
    ]
