# Generated by Django 3.2.6 on 2021-08-23 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcast', '0008_alter_episode_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='guest',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='episode',
            name='host',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='episode',
            name='link',
            field=models.URLField(max_length=300),
        ),
        migrations.AlterField(
            model_name='episode',
            name='tags',
            field=models.CharField(max_length=100),
        ),
    ]
