# Generated by Django 3.2.6 on 2021-08-28 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcast', '0009_auto_20210824_0043'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='summary',
            field=models.CharField(default='short summary', max_length=300),
        ),
    ]
