# Generated by Django 3.2.6 on 2021-12-11 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcast', '0012_episode_created_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='episodepic',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='episode',
            name='image',
            field=models.ImageField(default='ope_lau.jpg', upload_to='img/'),
        ),
    ]
