# Generated by Django 3.2.6 on 2022-01-08 21:33

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('podcast', '0013_auto_20211211_1750'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='slug',
            field=autoslug.fields.AutoSlugField(default='slug', editable=False, populate_from='title'),
        ),
    ]
