# Generated by Django 3.2.6 on 2022-01-12 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcast', '0014_episode_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='published_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
