# Generated by Django 3.2.6 on 2022-01-12 21:17

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('podcast', '0015_alter_episode_published_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
