# Generated by Django 3.2.6 on 2022-01-12 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcast', '0016_alter_episode_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='host',
            field=models.CharField(choices=[('Iniobong', 'Inibong Benson'), ('Opeyemi', 'Opeyemi Kazeem-Jimoh')], max_length=500),
        ),
    ]
