# Generated by Django 3.2.6 on 2022-01-16 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcast', '0017_alter_episode_host'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='embedurl',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='episode',
            name='host',
            field=models.CharField(choices=[('Iniobong Benson', 'Iniobong'), ('Opeyemi Kazeem-Jimoh', 'Opeyemi')], max_length=500),
        ),
    ]
