# Generated by Django 3.2.6 on 2022-01-31 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcast', '0019_alter_episode_embedurl'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='episode',
            name='embedurl',
        ),
        migrations.AlterField(
            model_name='episode',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='episode',
            name='host',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='episode',
            name='link',
            field=models.URLField(max_length=1500),
        ),
        migrations.AlterField(
            model_name='episode',
            name='published_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='episode',
            name='summary',
            field=models.CharField(max_length=1500),
        ),
    ]
