# Generated by Django 3.2.6 on 2022-01-31 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcast', '0020_auto_20220131_2149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='link',
            field=models.CharField(max_length=1500),
        ),
    ]
