# Generated by Django 3.2.6 on 2022-02-02 18:52

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('podcast', '0021_alter_episode_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
