# Generated by Django 3.2.6 on 2022-02-11 20:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('podcast', '0022_alter_episode_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='date_published',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
