# Generated by Django 3.2.6 on 2022-02-12 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcast', '0024_alter_episode_host'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='host',
            field=models.CharField(choices=[('Iniobong Benson', 'Iniobong'), ('Opeyemi Kazeem-Jimoh', 'Opeyemi')], max_length=500),
        ),
    ]
