# Generated by Django 3.2.6 on 2022-02-25 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcast', '0025_alter_episode_host'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='guest_bio',
            field=models.CharField(default='This is the guest bio', max_length=1000),
        ),
    ]
