# Generated by Django 3.2.6 on 2022-04-11 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcast', '0027_hosts'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tags', models.CharField(help_text='Enter a tag', max_length=30)),
            ],
        ),
        migrations.AlterModelOptions(
            name='hosts',
            options={'verbose_name_plural': 'Hosts'},
        ),
        migrations.AddField(
            model_name='episode',
            name='tag',
            field=models.ManyToManyField(help_text='select a tag', to='podcast.Tags'),
        ),
    ]
