# Generated by Django 3.2.6 on 2022-04-17 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('podcast', '0028_auto_20220411_0926'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tags',
            options={'verbose_name_plural': 'Tags'},
        ),
        migrations.RemoveField(
            model_name='episode',
            name='tags',
        ),
    ]
