# Generated by Django 3.2.6 on 2022-06-06 22:07

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('podcast', '0029_auto_20220417_2100'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='guest_image',
            field=cloudinary.models.CloudinaryField(default='', max_length=255, verbose_name='image'),
        ),
    ]
