# Generated by Django 3.2.6 on 2022-06-10 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcast', '0030_episode_guest_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='episode',
            name='episodepic',
        ),
        migrations.AlterField(
            model_name='episode',
            name='guest_image',
            field=models.ImageField(default='', upload_to='guest_image'),
        ),
        migrations.AlterField(
            model_name='episode',
            name='image',
            field=models.ImageField(default='ope_lau.jpg', upload_to='podcast_art/'),
        ),
        migrations.AlterField(
            model_name='episode',
            name='link',
            field=models.CharField(help_text='Provide link to episode audio', max_length=1500),
        ),
    ]
